AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Parameters:
  CognitoAuthorizerArn:
    Type: String
    Description: Reference to Cognito UserPool for the stage
  CustomDomain:
    Type: String
    Description: Custom API to connect this lambda to
  CustomDomainBasePath:
    Type: String
    Description: Base path mapping in CustomDomain
  CorsOrigin:
    Type: String
    Description: Value to use for Cors 'Allow...' header if value is set

Resources:

  NvaCristinProjectsFunctionApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !Ref CognitoAuthorizerArn
      Cors:
        AllowCredentials: true
        AllowOrigin: !Sub
          - "'${Domain}'"
          - Domain: !Ref  CorsOrigin
        AllowMethods: "'OPTIONS, GET'"
      EndpointConfiguration: Regional


  NvaCristinProjectsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Environment:
        Variables:
          AllowOrigin: !Sub
            - "${Domain}"
            - Domain: !Ref  CorsOrigin
      Handler: no.unit.nva.doi.FetchCristinProjects::handleRequest
      Runtime: java8
      MemorySize: 512
      Events:
        NvaCristinProjectsEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Auth:
              Authorizer: MyCognitoAuthorizer
            RestApiId: !Ref NvaCristinProjectsFunctionApi
            Path: /
            Method: post
            RequestParameters:
              - method.request.querystring.language
              - method.request.querystring.title

  NvaCristinProjectsFunctionBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Ref CustomDomainBasePath
      DomainName: !Ref CustomDomain
      RestApiId: !Ref NvaCristinProjectsFunctionApi
      Stage: !Ref NvaCristinProjectsFunctionApi.Stage

